pipeline {
   agent { label 'master' }

   environment {
       TERRAFORM_HOME = tool name: 'Terraform', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
    }   
    options {
        disableConcurrentBuilds()
        timeout(time: 1, unit: 'HOURS')
        ansiColor('xterm')
    }
    parameters {
        choice(
            choices: ['preview' , 'apply' , 'show', 'preview-destroy' , 'destroy'],
            description: 'Terraform action to apply',
            name: 'action')
        choice(
            choices: ['master' , 'dev' , 'qa', 'staging'],
            description: 'Choose branch to build and deploy',
            name: 'branch')
        string(name: 'bucket', defaultValue : 'subhakar-state-bucket', description: "Bucket name to store the tfstate file")
        string(name: 'region', defaultValue : 'us-west-2', description: "Region name where the bucket resides")
        string(name: 'cluster', defaultValue : 'demo-cloud', description: "EKS Cluster name")
        text(name: 'parameters', defaultValue : 'Please check the input https://github.com/SubhakarKotta/aws-eks-rds-terraform/blob/master/provisioning/terraform.tfvars', description: "EKS Cluster name")
    }
    
     stages {

         stage('Setup') {
             steps {
                script {
                    currentBuild.displayName = "#" + env.BUILD_NUMBER + " " + params.action + " - eks -" + params.cluster
                }
            }
        }

        stage('Git Checkout'){
            steps {
		      git url: 'https://github.com/SubhakarKotta/aws-eks-rds-terraform',branch: "${branch}"
          }
	    }

         
        stage('init') {
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") { 
                            writeFile file: "${cluster}-terraform.tfvars", text: "${parameters}"
                            sh '${TERRAFORM_HOME}/terraform version'
                            sh '${TERRAFORM_HOME}/terraform init -backend-config="bucket=${bucket}" -backend-config="key=${cluster}/terraform.tfstate" -backend-config="region=${region}"'
                            sh '${TERRAFORM_HOME}/terraform workspace new ${cluster} || true'
                            sh '${TERRAFORM_HOME}/terraform workspace select ${cluster}'
                        }
                    }
                }
            }
        }

        stage('validate') {
            when {
                expression { params.action == 'preview' || params.action == 'apply' || params.action == 'destroy' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") { 
                            sh '${TERRAFORM_HOME}/terraform validate --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }
        stage('preview') {
            when {
                expression { params.action == 'preview' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") {
                             sh '${TERRAFORM_HOME}/terraform plan --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }
       
        stage('apply') {
            when {
                expression { params.action == 'apply' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") {
                               sh '${TERRAFORM_HOME}/terraform plan -out=${cluster}-plan --var-file=${cluster}-terraform.tfvars'
                               sh '${TERRAFORM_HOME}/terraform apply -auto-approve ${cluster}-plan --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }

        stage('show') {
            when {
                expression { params.action == 'show' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") {
                               sh '${TERRAFORM_HOME}/terraform show --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }
        
        stage('preview-destroy') {
            when {
                expression { params.action == 'preview-destroy' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") {
                               sh '${TERRAFORM_HOME}/terraform plan -destroy --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }
       
        stage('destroy') {
            when {
                expression { params.action == 'destroy' }
            }
            steps {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',credentialsId: 'awsCredentials',accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY' ]]) {
                    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
                        dir ("provisioning") {
                            sh '${TERRAFORM_HOME}/terraform destroy -force --var-file=${cluster}-terraform.tfvars'
                        }
                    }
                }
            }
        }
    }
}