module "pega" {
  kubernetes_provider   = "eks"
  source                = "github.com/scrumteamwhitewalkers/terraform-pega-modules.git"
  cluster_name          = "${module.cluster.cluster_id}"
  chart_version         = "8.3.0-9"
  namespace             = "pega"
  release_name          = "pega"
  chart_name            = "pega"
  aws_access_key_id     = "${var.aws_access_key_id}"
  aws_secret_access_key = "${var.aws_secret_access_key}"
  deployment_timeout    = "7200"
  docker_password       = "${var.docker_password}"
  docker_username       = "${var.docker_username}"
  docker_url            = "https://index.docker.io/v1/"
  repo_url              = "https://scrumteamwhitewalkers.github.io/pega-helm-charts/"
  jdbc_url              = "jdbc:postgresql://${module.db.this_db_instance_endpoint}/${module.db.this_db_instance_name}"
}
